[[_the_resource_server_angular_js_and_spring_security_part_iii]]
= The Resource Server

In this section we continue <<_the_login_page_angular_js_and_spring_security_part_ii,our discussion>> of how to use http://projects.spring.io/spring-security[Spring Security] with http://angular.io[Angular] in a "single page application". Here we start by breaking out the "greeting" resource that we are using as the dynamic content in our application into a separate server, first as an unprotected resource, and then protected by an opaque token. This is the third in a series of sections, and you can catch up on the basic building blocks of the application or build it from scratch by reading the <<_spring_and_angular_js_a_secure_single_page_application,first section>>, or you can just go straight to the https://github.com/spring-guides/tut-spring-security-and-angular-js/tree/master/vanilla[source code in Github].

TIP: if you are working through this section with the sample application, be sure to clear your browser cache of cookies and HTTP Basic credentials. In Chrome the best way to do that for a single server is to open a new incognito window.

== A Separate Resource Server

=== Client Side Changes

On the client side there isn't very much to do to move the resource to a different backend. Here's the "home" component in the https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/single/src/app/home/component.ts[last section]:

.home.component.ts
[source,javascript]
----
@Component({
  templateUrl: './home.component.html'
})
export class HomeComponent {

  title = 'Demo';
  greeting = {};

  constructor(private app: AppService, private http: HttpClient) {
    http.get('resource').subscribe(data => this.greeting = data);
  }

  authenticated() { return this.app.authenticated; }

}
----

All we need to do to this is change the URL. For example, if we are going to run the new resource on localhost, it could look like this:

.home.component.ts
[source,javascript]
----
        http.get('http://localhost:9000').subscribe(data => this.greeting = data);
----

=== Server Side Changes

The https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/vanilla/ui/src/main/java/demo/UiApplication.java[UI server]
is trivial to change: we just need to remove the `@RequestMapping` for the
greeting resource (it was "/resource").
Then we need to create a new resource server, which we can do like we did in
the <<_spring_and_angular_js_a_secure_single_page_application,first section>>
using the https://start.spring.io[Spring Boot Initializr].
E.g. using curl on a UN*X like system:

[source]
----
$ mkdir resource && cd resource
$ curl https://start.spring.io/starter.tgz -d style=web \
-d name=resource | tar -xzvf -
----

You can then import that project (it's a normal Maven Java project by default) into your favourite IDE, or just work with the files and "mvn" on the command line.

Just add a `@RequestMapping` to the https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/vanilla/resource/src/main/java/demo/ResourceApplication.java[main application class], copying the implementation from the https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/single/src/main/java/demo/UiApplication.java[old UI]:

.ResourceApplication.java
[source,java]
----
@SpringBootApplication
@RestController
class ResourceApplication {

  @RequestMapping("/")
  public Message home() {
    return new Message("Hello World");
  }

  public static void main(String[] args) {
    SpringApplication.run(ResourceApplication.class, args);
  }

}

class Message {
  private String id = UUID.randomUUID().toString();
  private String content;
  public Message(String content) {
    this.content = content;
  }
  // ... getters and setters and default constructor
}
----

Once that is done your application will be loadable in a browser. On the command line you can do this

[source]
----
$ mvn spring-boot:run -Dserver.port=9000
----

and go to a browser at http://localhost:9000[http://localhost:9000] and you should see JSON with a greeting. You can bake in the port change in `application.properties` (in"src/main/resources"):

.application.properties
[source,properties]
----
server.port: 9000
----

If you try loading that resource from the UI (on port 8080) in a browser, you will find that it doesn't work because the browser won't allow the XHR request.

== CORS Negotiation

The browser tries to negotiate with our resource server to find out if it is
allowed to access it according to the
http://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross Origin Resource Sharing]
protocol.
It's not an Angular responsibility, so just like the cookie contract it will
work like this with all JavaScript in the browser.
The two servers do not declare that they have a common origin, so the browser
declines to send the request and the UI is broken.

To fix that we need to support the CORS protocol which involves a "pre-flight" OPTIONS request and some headers to list the allowed behaviour of the caller. Spring has some nice fine-grained CORS support, so we can just add an annotation to our controller mapping, for example:

.ResourceApplication.java
[source,java]
----
@RequestMapping("/")
@CrossOrigin(origins="*", maxAge=3600)
public Message home() {
  return new Message("Hello World");
}
----

NOTE: Blithely using `origins=*` is quick and dirty, and it works, but
it is not not secure and is not in any way recommended.

== Securing the Resource Server

Great! We have a working application with a new architecture. The only problem is that the resource server has no security.

=== Adding Spring Security

We can also look at how to add security to the resource server as a filter layer, like in the UI server. The first step is really easy: just add Spring Security to the classpath in the Maven POM:

.pom.xml
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
  </dependency>
  ...
</dependencies>
----

Re-launch the resource server and, hey presto! It's secure:

[source]
----
$ curl -v localhost:9000
< HTTP/1.1 401
< WWW-Authenticate: Basic realm="Realm"
...
----

In a browser we would get a redirect to a (whitelabel) login page, but the resource is just as secure. So all we need to do now is teach the client to send credentials with every request.

== Token Authentication

The internet, and people's Spring backend projects, are littered with custom token-based authentication solutions. Spring Security provides a barebones `Filter` implementation to get you started on your own (see for example https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilter.java[`AbstractPreAuthenticatedProcessingFilter`] and https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/token/TokenService.java[`TokenService`]). There is no canonical implementation in Spring Security though, and one of the reasons why is probably that there's an easier way.

== Conclusion

We have duplicated the features of the application in <<_the_login_page_angular_js_and_spring_security_part_ii,Part II of this series>>: a home page with a greeting fetched from a remote backend, with login and logout links in a navigation bar. The difference is that the greeting comes from a resource server that is a standalone, instead of being embedded in the UI server. This added significant complexity to the implementation, but the good news is that we have a mostly configuration-based (and practically 100% declarative) solution. We could even make the solution 100% declarative by extracting all the new code into libraries (Spring configuration and Angular custom directives). We are going to defer that interesting task for after the next couple of installments. In the <<_the_api_gateway_pattern_angular_js_and_spring_security_part_iv,next section>> we are going to look at a different really great way to reduce all the complexity in the current implementation: the API Gateway Pattern (the client sends all its requests to one place and authentication is handled there).

