[[_modular_angular_js_and_spring_security_part_vii]]
= Modular Angular Application

In this section we continue <<_spring_and_angular_js_a_secure_single_page_application,our discussion>> of how to use http://projects.spring.io/spring-security[Spring Security] with http://angularjs.org[Angular] in a "single page application". Here we show how to modularize the client-side code, and how to use "nice" URL paths which Angular uses by default, but which Spring MVC doesn't know about. This is the seventh section of a tutorial, and you can catch up on the basic building blocks of the application or build it from scratch by reading the <<_spring_and_angular_js_a_secure_single_page_application,first section>>, or you can just go straight to the https://github.com/dsyer/spring-security-angular/tree/master/modular[source code in Github]. We will be able to tidy up a lot of loose ends from the JavaScript code of the rest of this series, and at the same time show how it can fit very snugly against a backend server built from Spring Security and Spring Boot.

[[breaking-up-the-application]]
== Breaking up the Application

The sample application that we worked with so far in this series was trivial enough that we could get away with a single JavaScript source file for the whole thing. No larger application will ever end up that way, even if it starts out life like this one, so to mimic real life in a sample we are going to break things up. A good starting point would be to take the "single" application from the <<_the_login_page_angular_js_and_spring_security_part_ii,second section>> and have a look at its structure in the source code. Here's a directory listing for the static content (excluding the "application.yml" that belongs on the server):

-----------
static/
 js/
   hello.js
 app.html
 home.html
 login.html
 index.html
-----------

There are a few problems with this. One is obvious: all the JavaScript is in a single file (`hello.js`). Another is more subtle: we have HTML "partials" for views inside our application ("login.html" and "home.html") but they are all in a flat structure and not associated with the component code that uses them.

All the Angular code is actually already modularized into components ("app", "home" and "login"), and the components map nicely to the partials ("home.html" and "login.html" respectively). So let's break them out into those pieces:

-------------------
static/
  js/
    app/
      app.js
      app.html
    home/
      home.js
      home.html
    login/
      login.js
      login.html
    hello.js
  index.html
-------------------

The component definitions have moved into their own modules, alongside the HTML that they need to operate - nice and modular. If we had needed images or custom stylesheets we would have done the same with those.

NOTE: All the client-side code is under a single directory, "js" (except `index.html` because that is a "welcome" page and loads automatically from the "static" directory). This is intentional because it makes it easy to apply a single Spring Security access rule to all the static resources. These ones are all unsecured (because `/js/**` is unsecure by default in a Spring Boot application), but you might need other rules for other applications, in which case you would pick a different path.

For example, here's the `home.js`:

[source,javascript]
----
var HomeComponent = ng.core.Component({
    templateUrl : 'js/home/home.html'
}).Class({
    constructor : [AppService, ng.http.Http, function(app, http) {
        var self = this;
        this.greeting = {id:'', msg:''};
        http.get('resource').subscribe(response => self.greeting =response.json());
        this.authenticated = function() { return app.authenticated; };
    }]
});
----

and here's the new `hello.js`:

.hello.js
[source,javascript]
----
var RequestOptionsService = ng.core.Class({
    extends: ng.http.BaseRequestOptions,
    constructor : function() {},
    merge: function(opts) {
        opts.headers = new ng.http.Headers(opts.headers ? opts.headers : {});
        opts.headers.set('X-Requested-With', 'XMLHttpRequest');
        return opts.merge(opts);
    }
});

var routes = [
    { path: '', pathMatch: 'full', redirectTo: 'home'},
    { path: 'home', component: HomeComponent},
    { path: 'login', component: LoginComponent}
];

var AppModule = ng.core.NgModule({
    imports: [ng.platformBrowser.BrowserModule, ng.http.HttpModule,
            ng.router.RouterModule.forRoot(routes), ng.forms.FormsModule],
    declarations: [HomeComponent, LoginComponent, AppComponent],
    providers : [{ provide: ng.http.RequestOptions, useClass: RequestOptionsService }],
    bootstrap: [AppComponent]
  }).Class({constructor : function(){}});

document.addEventListener('DOMContentLoaded', function() {
    ng.platformBrowserDynamic.platformBrowserDynamic().bootstrapModule(AppModule);
});
----

Notice how the "hello" module _depends on_ the other two by listing them in the initial declarations. To make that work you just need to load the module definitions in the right order in `index.html`:

[source,html]
----
...
<script src="js/app/app.js" type="text/javascript"></script>
<script src="js/home/home.js" type="text/javascript"></script>
<script src="js/login/login.js" type="text/javascript"></script>
<script src="js/hello.js" type="text/javascript"></script>
...
----

This is the Angular dependency management system in action. Other frameworks have similar features. Also, in a larger application, you might use a build time step to bundle all the JavaScript together so it can be loaded efficiently by the browser, but that's almost a matter of taste.

[[using-natural-routes]]
== Using "Natural" Routes

The Angular `Router` by default works with URL paths that match the route, e.g. the login page is specified as a route in `hello.js` as "/login" and this translates into "/login" in the actual URL (the one you see in the browser window). This is awkward because it isn't bookmarkable, or refreshable. What we need to do in the backend is arrange that `index.html`, loaded via the root path "/", stays active on all routes. You can't do that if you have _only_ static resources, because `index.html` can only be loaded one way, but if you have some active components in the stack (a proxy or some server-side logic) then you can arrange for it to work by loading `index.html` from all the Angular routes.

In this series you have Spring Boot, so of course you have server-side logic, and using a simple Spring MVC controller you can naturalize the routes in your application. All you need is a a way to enumerate the Angular routes in the server. Here we choose to do it by a naming convention: all paths that do not contain a period (and are not explicitly mapped already) are Angular routes, and should forward to the home page:

[source,java]
----
@RequestMapping(value = "/{path:[^\\.]*}")
public String redirect() {
  return "forward:/";
}
----

This method just needs to be in a `@Controller` (not a `@RestController`) somewhere in the Spring application. We use a "forward" (not a "redirect") so that the browser remembers the "real" route, and that's what the user sees in the URL. It also means that any saved-request mechanisms around authentication in Spring Security would work out of the box, although we won't be taking advantage of that in this application.

NOTE: All the applications in the sample code already have this request mapping. It has been there all along if you were following along and using the code from github.

Coupled with that you need a `<base/>` element in the header of the HTML in `index.html`, and you need to make sure the links in the menu bar refer to the correct routes:

.index.html
[source,html]
----
<html>
<head>
<base href="/" />
...
</head>
<body ng-app="hello" ng-cloak class="ng-cloak">
...
</html>
----

.app.html
[source,html]
----
<div class="container">
  <ul class="nav nav-pills">
    <li><a routerLinkActive="active" routerLink="/home">Home</a></li>
    <li><a routerLinkActive="active" routerLink="/login">Login</a></li>
    <li><a (click)="logout()">Logout</a></li>
  </ul>
</div>
----

Angular uses the `<base/>` element to anchor the routes and write the URLs that show up in the browser. You are running in a Spring Boot application so the default setting is to serve from root path "/" (on port 8080). If you need to be able to serve from different root paths with the same application then you will need to render that path into the HTML using a server-side template (many people prefer to stick with static resources for a Single Page Application, so they are stuck with a static root path).

[[conclusion]]
== Conclusion

In this section we have seen how to modularize an Angular application (taking as a starting point the application from <<_the_login_page_angular_js_and_spring_security_part_ii,section two>> of the tutorial), how to make it redirect to a login page, and how to use "natural" routes that can be typed or bookmarked easily by users. We took a step back from the last couple of sections in the tutorial, concentrating on the client-side code a bit more, and temporarily ditching the distributed architecture that we were building in Sections III-VI. That doesn't mean that the changes here can't be applied to those other applications (actually it's fairly trivial) - it was just to simplify the server-side code while we were learning how to do things on the client. There _were_ a couple of server-side features that we used or discussed briefly though (for instance the use of a "forward" view in Spring MVC to enable "natural" routes), so we have continued the theme of Angular and Spring working together, and shown that they do so quite well with small tweaks here and there.
